name: Delete old Docker images

on:
  workflow_dispatch:
  registry_package:
    types: [published, updated]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: bookish-broccoli
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
